### ISSUE TITLE
Export as image

### ISSUE THREAD

**Issue by maverick74** [muriloventuroso/pdftricks#11]
Would be good if we could export a document as an image (jpeg, png, any...)

From what i understand, Ghostscript supports this.

I've been searching for this ( and apparently others too).

**Comment by muriloventuroso** [comment]
In progress

**Comment by maverick74** [comment]
@muriloventuroso taking a closer look on this, did it already support export as image before my bug report (and i missed it)? If so, i'm terribly sorry...

**Comment by muriloventuroso** [comment]
Yes, it already has support for converting pdf to png, jpg and txt. I'm trying to expand the supported formats and also convert in reverse, from image to pdf.
