### ISSUE TITLE
Merge images into pdf

### ISSUE THREAD

**Issue by peteruithoven** [muriloventuroso/pdftricks#17]
Thanks for this great application! 
PDF Tricks already supports converting pdf's to jpg, png and txt formats, I'd love to also be able to convert multiple images (png / jpg) into a pdf. 
I've tried using the Merge PDF functionality, which allowed selecting images:
![screenshot from 2019-02-05 14 28 07](https://user-images.githubusercontent.com/523210/52278301-038d5b80-2957-11e9-9dd3-a37dce85e1c5.png)
But the merging failed.

**Comment by muriloventuroso** [comment]
The merge function works only for PDF files. But this is a very interesting suggestion. I'll try to implement for the next release.

**Comment by peteruithoven** [comment]
Thanks!

**Comment by Hedronmx** [comment]
How can I use this? I updated to latest version. Thanks!

**Comment by muriloventuroso** [comment]
You need to check the policies of your ImageMagick installation.

Find and edit the configuration file.

`/etc/ImageMagick-7/policy.xml`
To check the ImageMagick version:

`convert --version`
Find the line that contains the rule for PDF files:

`<policy domain="coder" rights="none" pattern="PDF" />`
And change to:

`<!-- <policy domain="coder" rights="none" pattern="PDF" /> -->`
And ready!

If you are using the flatpak version no changes are required, it is already ready for use.

**Comment by Hedronmx** [comment]
Yeah, already did that but how do I use it in the program?

**Comment by peteruithoven** [comment]
Have you tried going to the Merge PDF page, adding the images and pressing merge?

**Comment by Hedronmx** [comment]
Oh I thought that was just for pdfs! Thought a button was missing. Maybe add that you can merge images as well!

Thanks!
