### ISSUE TITLE
Merge always fails

### ISSUE THREAD

**Issue by freaktechnik** [muriloventuroso/pdftricks#21]
When trying to merge two PDF files with one page each I always get an error. No idea what exactly is wrong, I've tried them with multiple names and file sizes, but I can never get it to actually merge.

**Comment by muriloventuroso** [comment]
Have you adjusted ImageMagick security policies as Readme instructions?

**Comment by freaktechnik** [comment]
I have not read any readme, since I have installed it from the app store and assumed it would work. I have now used pdfunite in the CLI which worked just fine.

**Comment by muriloventuroso** [comment]
The application description also contains a warning about the need for this change. Unfortunately it is an inconvenient application by ImageMagick. Using the flatpak package available on FlatHub is not necessary to make this change, it is already done in the package.

**Comment by freaktechnik** [comment]
I'd expect the application to at least give a meaningful warning telling me to adjust my image magick settings or whatever. But thanks for the heads up.
