### ISSUE TITLE
Compression UI is confusing

### ISSUE THREAD

**Issue by freaktechnik** [muriloventuroso/pdftricks#22]
"Resolution to compress high" isn't really a statement that tells me what the compression will do. From what I can tell you chose the final resolution, and if that's "high" or "low", whatever either of those mean. I assume this optimizes for a certain pixel density, high being for print and low for screen viewing?

**Comment by muriloventuroso** [comment]
High resolution means that the optimization will do its best to keep the resolution close to the original.

**Comment by freaktechnik** [comment]
So it really is "Compression resolution target: As high as possible" (with some limitations, since it does have some other constraints, clearly) and low is something else.

**Comment by muriloventuroso** [comment]
Yep! Certainly an adjustment on that is welcome. The user needs to understand clearly what application will do.

**Comment by muriloventuroso** [comment]
I renamed the attribute to Compression Level (more understandable) and added a short description of the differences. We also have an intermediate level, for those who have doubts. :)
