### ISSUE TITLE
Text becomes unselectable after merging

### ISSUE THREAD

**Issue by Appeltabak** [muriloventuroso/pdftricks#27]
The application uses `convert` to merge the PDF files, which converts the page into images and therefore making previously selectable text unselectable. Is the there a specific reason why `convert` is used and not `gs`, like with the splitting option?

**Comment by muriloventuroso** [comment]
With convert you can include images in the merge. I did not have much success in this kind of operation with gs

**Comment by Appeltabak** [comment]
When I execute `gs -dNOPAUSE -sDEVICE=pdfwrite -sOUTPUTFILE=combined.pdf -dBATCH file-1.pdf file-2.pdf` I was able to merge two pdf's with images successfully. What went exactly wrong when you tried to merge with `gs`?

**Comment by muriloventuroso** [comment]
It would not image inside PDF and yes image directly. Merge PDF + PNG. I'm implementing an alternate way to fix this. When there are image files to merge with PDF I will first convert the image to PDF and then merge with the gs.

**Comment by Appeltabak** [comment]
A, alright, it wasn't obvious to me that images were allowed. Just saw the 'Merge PDF' subtext mentioning it. My bad :grin: Looking forward for your fix
