### ISSUE TITLE
Suggestion to utilize QPDF as a backend for your application

### ISSUE THREAD

**Issue by Nokia808** [muriloventuroso/pdftricks#28]
Hi. I would like to suggest on you to utilize QPDF as a backend for your application. Moreover, it is of only very few bugs.

QPDF is very powerful PDF command line tool that has very powerful abilities. It's developer ready to assist any one like to create a GUI for it.

See it's page & read about it's functionality:
https://github.com/qpdf/qpdf

**Comment by muriloventuroso** [comment]
Unfortunately I don't have time for a drastic change in this project. But of course if any develops suggest and take responsibility for a change of engine I will be glad to support.
