### ISSUE TITLE
Suggestion to utilize OCRmyPDF as a backend !

### ISSUE THREAD

**Issue by Nokia808** [muriloventuroso/pdftricks#35]
Hi. your program already has options to change resolution of PDF. So, I thing you are interested in add new options for "Optimize scanned PDF". If yes, then I suggest on you to utilize very powerful command line program called OCRmyPDF - see it at:

https://github.com/jbarlow83/OCRmyPDF
&
https://pypi.org/project/ocrmypdf/

**Comment by muriloventuroso** [comment]
Unfortunately I don't have time for a drastic change in this project. But of course if any develops suggest and take responsibility for a change of engine I will be glad to support.
