### ISSUE TITLE
Kindly see this tool if your are interested to fork it & complete it's development !

### ISSUE THREAD

**Issue by Nokia808** [muriloventuroso/pdftricks#36]
Hi. There is already very excellent PDF manipulation tool available for Linux. But unfortunately it's developer stop from developing it since long time & have no interest to re-working on it. It need some new features to be added to it & create a viewers (or in fact co-ordinate with it an already existing viewer) before becoming a real Adobe acrobat pro alternative on Linux .....

It is available here:
https://sourceforge.net/projects/jpdftweak/
to see it's powers please look at:
http://jpdftweak.sourceforge.net/manual/index.html

it need to add just about 10 new features/enhancements to be really really an alternative to adobe acrobat pro .......

I asked others to do this but they refuse for just being a java application ......

**Comment by muriloventuroso** [comment]
Unfortunately I don't have time and I'm not very familiar with Java either.
