### ISSUE TITLE
Upcoming release?

### ISSUE THREAD

**Issue by toxpal** [muriloventuroso/pdftricks#46]
Not a "real" issue, but I was wondering if this project is still maintained? For example, I suggested some missing features almost a year ago, and commits were added very shortly. Unfortunately, no new release with new features was ever made. I'm sure many more commits were added since the last release last year, and it would be great to have them available for use.

**Comment by muriloventuroso** [comment]
My time is very short, I am not able to give so much attention to this project. Most of the commits since the last release have been for translation. But I will release a new version today.
