### ISSUE TITLE
provide .exe package 

### ISSUE THREAD

**Issue by Lvaskz** [muriloventuroso/pdftricks#9]
Hi, This tool can be usefull for windows user. Personally speaking I use mint 19.1 but in the office they use windows.
Can you provide .exe package or zip? 
thanks

**Comment by fitojb** [comment]
This is a Gtk+ program written in Vala with elementary OS’ Granite library. None of that is portable to Windows without requiring a complete rewrite. Have you tried [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)?

**Comment by Lvaskz** [comment]
No, but no matter.

thanks
